---
title: "Swedish Bird Recoveries"
author: ""
date: "`r Sys.Date()`"
output: rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{Swedish Bird Recoveries}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Swedish Bird Recoveries provide data and graphs for recovered birds which were originally marked with a ring in Sweden.

```{r, fig.show='hold', warning=FALSE, message=FALSE}

library(leaflet)
library(swedishbirdrecoveries)

# use just 100 or so points here
birds <- 
  birdrecoveries_eng[1:100, ] %>%
  dplyr::rename(longitude = ringing_lon,
         latitude = ringing_lat)

# content in popup can be customized
popup_content <- #htmltools::htmlEscape(
  paste(sep = "<br/>",
    "<b><a href='http://nrm.se'>NRM</a></b>",
    "<b>Name:</b>", birds$name
)

map <- 
  leaflet(data = birds) %>% 
  # base groups
  addProviderTiles("OpenStreetMap.BlackAndWhite", group = "Gray") %>% 
  addProviderTiles("Stamen.TonerLite", group = "Black & White") %>%
#  addMarkers(~longitude, ~latitude, popup = ~as.character(dgr), group = "Individual") %>%
  addMarkers(~longitude, ~latitude, popup = popup_content,
             clusterOptions = markerClusterOptions(), group = "Clustered") %>%
  addLayersControl(
    baseGroups = c("Gray", "Black & White"),
#    overlayGroups = c("Individual", "Clustered"),
    options = layersControlOptions(collapsed = FALSE)
  )

map

```

This clustered map shows 100 recaptured birds originating from Falsterbo bird station. 

# Investigate using tilegrams

http://rpubs.com/bhaskarvk/tilegramsR

# Intro to swedishbirdrecoveries

A programmatic interface to the Swedish Bird Recaptures database at the Swedish Museum for Natural History.

With this package you can work with the recapture bird data and also create graphs and explore the dataset.

## Installation

You can get started by installing the development version from Github and loading it: 

```r
install.packages("devtools")
devtools::install_github("mskyttner/swedishbirdrecoveries")

library("rebird")
```

## Usage

Search for bird recaptures by location (lat/lon), possibly with additional parameter settings, returning only 10 records, includes or excludes: 

```r
# ebirdgeo(lat = 42, lng = -76, max = 10, includeProvisional = TRUE, hotspot = TRUE)
```

Search using location IDs or by location ID and species name etc:

```r
# ebirdloc(locID = c('L99381','L99382'))

# ebirdloc(locID = 'L99381', species = 'larus delawarensis', max = 10, provisional = TRUE, hotspot=TRUE)
```

Search by region and species name and using additional parameters:

```r
# ebirdregion(region = 'US', species = 'Setophaga caerulescens')
# Note that we use `US-OH` to represent Ohio within the US. [See possible region values](https://confluence.cornell.edu/display/CLOISAPI/eBird-1.1-RegionCodeReference).
# ebirdregion(region = 'US-OH', max = 10, provisional = TRUE, hotspot = TRUE)
```

Search recent data by region and species name:

```r
#ebirdhotspot(locID = c('L99381','L99382'), species = 'larus delawarensis')
```

Obtain historical frequencies at a given hotspot or state or country, or time period, resuls can also be wide for making bar charts

```r
#ebirdfreq(loctype = 'hotspots', loc = 'L196159')
#ebirdfreq(loctype = 'hotspots', loc = 'L196159', long = FALSE)
#ebirdfreq(loctype = 'states', loc = 'CA-BC')
#ebirdfreq(loctype = 'counties', loc = 'CA-BC-GV')
#ebirdfreq(loctype = 'hotspots', loc = 'L196159', startyear = 2010,
          endyear = 2014, startmonth = 1, endmonth = 3)
```

Search for notable sightings at a given latitude and longitude

```r
#ebirdnotable(lat = 42, lng = -70)
```

Return a data.frame of all species in the eBird taxonomy for the given parameter inputs

```r
# ebirdtaxonomy()
```

Check if a region is valid or get a data frame of regions or localities....


